### ISSUE TITLE
[김민정의 WTD]

### ISSUE THREAD

**Issue by loafcheck** [likeLion-FE-6/WTD#11]
## 오늘 일정 (22.10.27)

양식은 다음과 같이 써주세요. 해당 주석은 지워주세요
- [ ] `19:00-20:00` 6조 회고하기
- [ ] `20:10-21:30` 페어프로그래밍

**Comment by ssujinchoi** [comment]
언니 영어발음이 완전 뉴욕크재질이얌~ 쏘 프맅티 아임 인 뉴요크 나우!!
