### ISSUE TITLE
11월 2주차- [백경현의 WTD]

### ISSUE THREAD

**Issue by gyeongbaek** [likeLion-FE-6/WTD#27]
## 22. 11. 07. 월
- [x]  `1-2` 노션 템플릿 완성
- [x]  `16-17` 집필 피드백 및 수정
- [x]  `17-18` 작우소 회의 준비
- [x]  `18-19` 작우소 회의
- [x]  `21-22` SPA 마무리
- [ ]  `22-24` 1만시간 복습

## 오늘 일정이 다 끝난 후에는 인증샷을 남겨주세요

![스크린샷 2022-11-08 오후 4 46 46](https://user-images.githubusercontent.com/96777064/200504682-9b8b8b53-f3ec-4ee5-8891-2375c2ba3f37.png)
모니터암과 카페인만 있다면 어디든 갈 수 있어. 목이랑 등 안아프니까 삶의 질 수직상승이다.

**Comment by baeggoose** [comment]
작우소가 뭐야? 작은 우리의 소리? 작고 우직한 소?

**Comment by gyeongbaek** [comment]
> 작우소가 뭐야? 작은 우리의 소리? 작고 우직한 소?

우리 스터디 이름ㅋㅋㅋㅋ 부끄러우니까 뜻은 얘기하지 않겠어 ^~^

**Comment by gyeongbaek** [comment]
## 22. 11. 08. 화
- [x]  `1-2` 폴더 구조 생성(레포 업로드)
- [x]  `2-3` 설문조사 준비(이미지)
- [x]  `9-12` JS 시험
- [ ]  `16-17` 복습  `-> 20`
- [x]  `17-18` 회의
- [x] `18-20` 휴식 `9시반에 일어났다..휴`
- [ ] `20-22` 리액트 복습
- [ ] `22-24` 페이지 구현

## 오늘 일정이 다 끝난 후에는 인증샷을 남겨주세요
![image](https://user-images.githubusercontent.com/96777064/200504993-08431683-1f20-4dd2-a288-a361d9c55690.png)
오늘의 최고 이슈는 시험이지 않을까? 오전 시간 하얗게 불태우고, 오후에 영혼 나간채로 앉아있었다.
어제 늦게 자기도 했고,, 아무튼 잠깐 자고 일어나서 오늘 수업 파트 공부하려고 했는데 그냥 계속 잤다. 프사값 하는 중...

**Comment by gyeongbaek** [comment]
## 22. 11. 09. 수
- [x]  `6-7` 리액트 공부
- [x]  `16-17` 집필회의
- [x]  `17-18` 스터디 회의
- [x]  `22-23` 피그마 수정 및 페이지 제작
- [ ]  `23-1` 블로그 내용 정리


## 오늘 일정이 다 끝난 후에는 인증샷을 남겨주세요
<img width="744" alt="image" src="https://user-images.githubusercontent.com/96777064/200883341-35e24cf1-fc3e-4a4c-8572-65b21a978bcf.png">
내 밤공 메이트: 카페인과 몬엑 플리 1.25 배속. 코딩 부순다
6시에 일어나서 리액트 1시간 보고 잤다가 8시반에 다시 일어났다. 최악의 효율이다. 그냥 적당히 일찍 일어나야지.

**Comment by gyeongbaek** [comment]
## 22. 11. 09. 목
- [ ]  `7-8` 모닝페이지 쓰고 운동
- [x]  `8-9` SPA 손필기
- [ ]  `16-17` 주간회고록 작성
- [ ]  `17-18` 주간회의
- [ ]  `19-20` 요가
- [ ]  `21-20` 스타일 코드 작성
- [ ]  `20-` 컴포넌트 분리


## 오늘 일정이 다 끝난 후에는 인증샷을 남겨주세요

**Comment by baekg6** [comment]
## 22. 11. 09. 금
해피 휴강

## 오늘 일정이 다 끝난 후에는 인증샷을 남겨주세요

**Comment by gyeongbaek** [comment]
## 주간회고
### 일상
- 템플릿 완성
수빈님이 쓰시는 노션 템플릿 고쳐가지고 쓰고있다. 저번주는 깃허브에 WTD 쓰는걸 자꾸 까먹었는데 아침에 노션에 쓰고, 그대로 복붙하고(마크다운이라 안 깨진다) 노션에 WTD랑 세부사항 정리하고 자기전에 한 일 체크하니까 좀 꾸준히 쓰게 된 것 같다. 템플릿으로 작성할 거 나눠놓으니까 어디에 적어야지 하고 고민하는 시간이 없어지면서 효율적으로 잘 쓰게 되는 것 같다. 프로젝트 문서는 좀 더 다듬어서 템플릿 정리해둬야겠다.  


- 바른자세
멋사 초반에 강사님들이 장비 사라고 하셨을 때 약간 이해 못했는데 직접 겪으니까 알겠다. 꾸준히 요가하는데도 수업만 끝나면 목+어깨+등이 너무 아팠는데 모니터암 설치하고 공부할 때 바른 자세 하니까 아프지도 않고 요가할때 안되던 동작들도 무리없이 하고 있다. 글쓰거나 하면 자세 흐뜨러지지만 의식적으로 바른 자세 해야지


### 공부
- 집중하기
이번주는 정말 집중을 못했다. 화요일에 시험 끝난 이후로 긴장이 풀린 건지, 갑자기 리액트+노드 달리니까 감을 못잡아서 그런건지, 이번주는 내내 붕 떠 있는 기분이었다. 쉰 만큼 다시 움직이자.

- 실습
이론적으로 내용을 정리하는 것도 중요하지만 확실히 부딪히면서 기록해둔게 오래 기억에 남는다. 내용을 다 외우진 못하고 '아 이거 그때 나왔는데?' 하고 정리한 걸 찾아보는 정도. 실제로 하면서 부딪힌 문제를 풀어가면서 배우는 게 큰 것 같다. 그리고 중요한 건 기록해두는 것. 비공개로 올렸던 글들 공개로 돌릴 수 있게 다듬고 내용 보충하기.

### 프로젝트
- 집필
집필이 끝났다. 표절률 5%. 집필 퇴고한 기억들이 주마등이 처럼 스쳐지나가고, 크게 부담이 되었던 건 아니지만 그래도 끝나니까 좋다. 깊게 공부해보고 싶던 주제였는데 내 언어로 풀면서 확실히 내용을 이해한 것 같다. (또 늘어나는 기록의 중요성) 아무튼 얼른 책 나왔으면 좋겠다. 책 나오면 이력서에 올려둬야지.

- 작우소 프로젝트
컨벤션 같은 거 다 맞추고 프로젝트를 시작했는데도 협의할 내용이 정말 많다. 다행히 큰 부담은 아니고, 생각보다 재밌고 부담이 적다. 지금 SPA 강의 하는 그 파트랑 딱 시기가 잘 맞물린 느낌? 그래도 SPA 강의 한번 더 정리하긴 해야할 것 같다. 영상 강의는 코딩 하다가 헷갈리는 부분 바로 찾기는 어려우니까 어디든 정리해둬야지. 이번 프로젝트 덕분에 멋사 프로젝트 하면서 초반 협의는 빠릿빠릿하게 할 수 있을 듯(제발)

---
### To DO
- [ ] 블로그 포스팅 정리용 노션 페이지
- [ ] 깃허브 레포정리 + 리드미 작성(*양식작성)
- [ ] 프로젝트 진행

**Comment by Jxxunnn** [comment]
굿 집필하느라 고생하셨고, 프로젝트 열심히 하시길 바랍니다!
